import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";

import "./globals.scss";
import "@styles/main.scss";

import { Header } from "@/components/Header";
import Footer from "@/components/Footer";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QPD — студия разработки",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={comfortaa.className}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
